services:
  mongodb:
    image: 'mongo:latest'
    environment:
      - 'MONGO_INITDB_DATABASE=mongo_db'
      - 'MONGO_INITDB_ROOT_PASSWORD=secret'
      - 'MONGO_INITDB_ROOT_USERNAME=root'
    ports:
      - '27018:27017'
  app:
    build: ./src/main/resources/Dockerfile
    ports:
      - '8081:8080'
    environment:
      - 'SPRING_DATA_MONGODB_URI=mongodb://root:secret@mongodb:27017/mongo_db'
    depends_on:
      - mongodb
